services:
  - type: web
    name: yahoo-finance-scraper
    env: python
    buildCommand: pip install -r render-requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --reuse-port main:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: CACHE_TYPE
        value: SimpleCache
      - key: CACHE_DEFAULT_TIMEOUT
        value: 1800
      - key: LOG_LEVEL
        value: INFO
    autoDeploy: true